#!/bin/bash
# Script to help reproduce the 'crnull' results for session 20200327
#
# The 'crnull' folder was created before tagged axes existed, which means it used
# legacy axes at axes/axes_{AREA}.npz. We need to determine:
# 1. What orientation were those axes trained on? (vertical, horizontal, or pooled)
# 2. What orientation were the flow trials? (vertical, horizontal, or pooled)

set -e  # Exit on error

SID="20200327"
OUT_ROOT="out"
ALIGN="stim"
LAGS_MS=50.0
RIDGE=0.01
PERMS=500
PT_MIN=200.0

echo "============================================================"
echo "Reproducing 'crnull' for session $SID"
echo "============================================================"
echo ""

# Test Scenario A: Vertical axes, pooled flow
echo "Test Scenario A: Train axes on VERTICAL, compute flow on POOLED"
echo "----------------------------------------------------------------"
echo ""
echo "Step 1: Train axes on vertical trials"
echo "python cli/train_axes.py \\"
echo "  --out_root $OUT_ROOT \\"
echo "  --align $ALIGN \\"
echo "  --sid $SID \\"
echo "  --orientation vertical \\"
echo "  --features C R \\"
echo "  --pt_min_ms $PT_MIN"
echo ""
echo "Step 2: Compute flow on pooled trials (using vertical axes)"
echo "for FEAT in C R; do"
echo "  python cli/flow_session.py \\"
echo "    --out_root $OUT_ROOT \\"
echo "    --align $ALIGN \\"
echo "    --sid $SID \\"
echo "    --feature \$FEAT \\"
echo "    --orientation pooled \\"
echo "    --tag crnull-test-A \\"
echo "    --lags_ms $LAGS_MS \\"
echo "    --ridge $RIDGE \\"
echo "    --perms $PERMS \\"
echo "    --pt_min_ms $PT_MIN"
echo "done"
echo ""
echo "Step 3: Compare with original"
echo "python3 << 'EOF'"
echo "import numpy as np"
echo "orig = np.load('$OUT_ROOT/$ALIGN/$SID/flow/crnull/C/flow_C_MFEFtoMLIP.npz', allow_pickle=True)"
echo "test = np.load('$OUT_ROOT/$ALIGN/$SID/flow/crnull-test-A/C/flow_C_MFEFtoMLIP.npz', allow_pickle=True)"
echo "diff = np.nanmax(np.abs(orig['bits_AtoB'] - test['bits_AtoB']))"
echo "print(f'Max difference: {diff}')"
echo "if diff < 1e-10:"
echo "    print('MATCH! Scenario A is correct.')"
echo "else:"
echo "    print('NO MATCH. Try Scenario B.')"
echo "EOF"
echo ""
echo ""

# Test Scenario B: Pooled axes, pooled flow
echo "Test Scenario B: Train axes on POOLED, compute flow on POOLED"
echo "----------------------------------------------------------------"
echo ""
echo "Step 1: Train axes on pooled trials"
echo "python cli/train_axes.py \\"
echo "  --out_root $OUT_ROOT \\"
echo "  --align $ALIGN \\"
echo "  --sid $SID \\"
echo "  --orientation pooled \\"
echo "  --features C R \\"
echo "  --pt_min_ms $PT_MIN"
echo ""
echo "Step 2: Compute flow on pooled trials"
echo "for FEAT in C R; do"
echo "  python cli/flow_session.py \\"
echo "    --out_root $OUT_ROOT \\"
echo "    --align $ALIGN \\"
echo "    --sid $SID \\"
echo "    --feature \$FEAT \\"
echo "    --orientation pooled \\"
echo "    --tag crnull-test-B \\"
echo "    --lags_ms $LAGS_MS \\"
echo "    --ridge $RIDGE \\"
echo "    --perms $PERMS \\"
echo "    --pt_min_ms $PT_MIN"
echo "done"
echo ""
echo "Step 3: Compare with original"
echo "python3 << 'EOF'"
echo "import numpy as np"
echo "orig = np.load('$OUT_ROOT/$ALIGN/$SID/flow/crnull/C/flow_C_MFEFtoMLIP.npz', allow_pickle=True)"
echo "test = np.load('$OUT_ROOT/$ALIGN/$SID/flow/crnull-test-B/C/flow_C_MFEFtoMLIP.npz', allow_pickle=True)"
echo "diff = np.nanmax(np.abs(orig['bits_AtoB'] - test['bits_AtoB']))"
echo "print(f'Max difference: {diff}')"
echo "if diff < 1e-10:"
echo "    print('MATCH! Scenario B is correct.')"
echo "else:"
echo "    print('NO MATCH. Check parameters.')"
echo "EOF"
echo ""
echo ""

# Test Scenario C: Horizontal axes, pooled flow
echo "Test Scenario C: Train axes on HORIZONTAL, compute flow on POOLED"
echo "----------------------------------------------------------------"
echo ""
echo "Step 1: Train axes on horizontal trials"
echo "python cli/train_axes.py \\"
echo "  --out_root $OUT_ROOT \\"
echo "  --align $ALIGN \\"
echo "  --sid $SID \\"
echo "  --orientation horizontal \\"
echo "  --features C R \\"
echo "  --pt_min_ms $PT_MIN"
echo ""
echo "Step 2: Compute flow on pooled trials (using horizontal axes)"
echo "for FEAT in C R; do"
echo "  python cli/flow_session.py \\"
echo "    --out_root $OUT_ROOT \\"
echo "    --align $ALIGN \\"
echo "    --sid $SID \\"
echo "    --feature \$FEAT \\"
echo "    --orientation pooled \\"
echo "    --tag crnull-test-C \\"
echo "    --lags_ms $LAGS_MS \\"
echo "    --ridge $RIDGE \\"
echo "    --perms $PERMS \\"
echo "    --pt_min_ms $PT_MIN"
echo "done"
echo ""
echo ""

echo "============================================================"
echo "SUMMARY"
echo "============================================================"
echo ""
echo "The 'crnull' folder has NO corresponding axes folder, which means it"
echo "used the LEGACY axes at axes/axes_{AREA}.npz"
echo ""
echo "To reproduce, you need to:"
echo "1. Backup current legacy axes if they exist:"
echo "   mkdir -p $OUT_ROOT/$ALIGN/$SID/axes_backup"
echo "   cp $OUT_ROOT/$ALIGN/$SID/axes/axes_*.npz $OUT_ROOT/$ALIGN/$SID/axes_backup/ 2>/dev/null || true"
echo ""
echo "2. Run one of the test scenarios above"
echo ""
echo "3. Compare results to find which matches"
echo ""
echo "My hypothesis: Scenario A (vertical axes, pooled flow) is most likely"
echo "because:"
echo "  - Default orientation is 'vertical'"
echo "  - 'crnull-vertical' and 'crnull-horizontal' were created later"
echo "  - The name 'crnull' (no orientation suffix) suggests pooled trials"
echo ""
echo "See CRNULL_RECONSTRUCTION_GUIDE.md for more details."

